[project]
name = "aoc"
authors = [{ name = "Aidan Buie" }]
version = "0.1.0"
description = "Advent of code soltuions."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.1.3",
]

[dependency-groups]
dev = [
    "mypy>=1.13.0",
]
